
all: example example_thread

example: example.c
	gcc -I../.. -L../.. -o example example.c -lpinggy

example_thread: example_thread.c
	gcc -I../../ -L../.. -o example_thread example_thread.c -lpinggy
