name: macOS Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-macos:
    name: macOS Package
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Download OpenSSL
      run: |
        wget https://8000.lvpn.abhijitmondal.in/OpenSSL.tgz
        tar -xzf OpenSSL.tgz

    - name: LS
      run: ls -lrt .

    # - name: Set up CMake
    #   uses: lukka/get-cmake@v3

    # - name: Make script executable
    #   run: chmod +x ./build_macos.sh

    - name: Run build script
      run: |
        OPENSSL_ROOT_PATH="${{ github.workspace }}/OpenSSL/3.3.1/universal" bash -x crossbuilding/macos/buildForMacos.sh

    - name: LS
      run: ls -lrt .

    # - name: Upload release artifact
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: dist/*.tgz  # or wherever your script puts output
