name: Build in Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run build in container
      run: |
        bash crossbuilding/linux/buildForLinux.sh
    - name: List
      run: ls
    - name: List
      run: tree .
