name: Build in Windows

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Only fetch latest commit (faster)

    - name: Fetch tags separately
      run: git fetch --tags

    - name: Download and extract .zip file
      run: |
        $url = "https://public-pre-built-libraries.s3.us-east-2.amazonaws.com/openssl/OpenSSL-3.3.1-windows.zip"
        $zipPath = "$env:GITHUB_WORKSPACE\OpenSSL-3.3.1-windows.zip"
        $extractPath = "$env:GITHUB_WORKSPACE"
        Invoke-WebRequest -Uri $url -OutFile $zipPath
        Expand-Archive -Path $zipPath -DestinationPath $extractPath

    - name: Configure and build
      run: |
        echo "OPENSSL_DIR=${{ github.workspace }}\OpenSSL" >> $env:GITHUB_ENV
        echo "RELEASE_DIR=${{ github.workspace }}\releases" >> $env:GITHUB_ENV

    - name: Configure cmake env
      run: |
        echo "CMAKE_EXE=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" >> $env:GITHUB_ENV
        echo "WINDOWS_SDK_VERSION=10.0.19041.0" >> $env:GITHUB_ENV

    - name: Build with bundled CMake
      run: cmd.exe /c "crossbuilding\windows\buildForWindows.bat %OPENSSL_DIR% releases
      shell: cmd

    - name: List all files in workspace
      run: |
        Get-ChildItem -Path "$env:GITHUB_WORKSPACE\releases" -Recurse
