name: Build in Runner (Windows)

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and extract .tgz file
      run: |
        $url = "https://public-pre-built-libraries.s3.us-east-2.amazonaws.com/openssl/openssl_windows_all_arch.zip"
        $zipPath = "$env:GITHUB_WORKSPACE\openssl_windows_all_arch.zip"
        $extractPath = "$env:GITHUB_WORKSPACE"
        Invoke-WebRequest -Uri $url -OutFile $zipPath
        Expand-Archive -Path $zipPath -DestinationPath $extractPath

    - name: List all files in workspace
      run: |
        Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse

    - name: Configure and build
      run: |
        echo "DIR_PATH=${{ github.workspace }}\\OpenSSL" >> $env:GITHUB_ENV

    - name: Build with bundled CMake
      run: |
        "crossbuilding\windows\buildForWindows.bat" $env:DIR_PATH build releases
    #    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build build --config Release

    - name: List all files in workspace
      run: |
        Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse