name: Build in Linux (container)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Only fetch latest commit (faster)

    - name: Fetch tags separately
      run: git fetch --tags

    - name: Run build in container
      run: |
        bash crossbuilding/linux/buildForLinux.sh
    - name: List
      run: ls
    - name: List
      run: tree .
